apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 100Mb
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs
    server: 10.0.0.244