---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: pv-nfs
# provisioner: nfs.csi.k8s.io
# parameters:
#   server: 10.0.0.244
#   share: /srv/nfs
# reclaimPolicy: Delete
# volumeBindingMode: Immediate
# mountOptions:
#   - hard
#   - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs
    server: 10.0.0.244