apiVersion: apps/v1
kind: pods
metadata:
  name: tools
  labels:
    app: tools
spec:
  containers:
  - name:  tools
    image:  ichte/coretools
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]