apiVersion: v1
kind: Pod
metadata:
  name: arm-tools
  labels:
    app: arm-tools
spec:
  containers:
  - name: tools
    image: apteno/alpine-jq
    resources: {}
    # command: ["/bin/bash"]
    # args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]